services:
  - type: web
    name: server-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npx prisma migrate deploy
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: "10000"
    autoDeploy: true
