services:
  - type: web
    name: server-app
    env: node
    region: singapore
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../node && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
