services:
  - type: web
    name: server-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
      npx prisma generate
      npx prisma migrate deploy
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: "10000"
    disk:
      name: backend-disk
      sizeGB: 1
    autoDeploy: true

  - type: web
    name: server-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm run preview -- --port 3001
    envVars:
      - key: PORT
        value: "3001"
    autoDeploy: true
