services:
  - type: web
    name: server-backend
    env: node
    plan: free
    buildCommand: npm run install:all
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
    autoDeploy: true
